### ISSUE TITLE
画像のwebp化の対応

### ISSUE THREAD

**Issue by hisamikurita** [liginc/wp-starter-theme#1]

**Comment by uemaSR** [comment]
npm scriptで独立させて実行をプルリク出してます。

viteのimageminプラグインにwebp対応のも入ってるけど、圧縮はできても変換は無いっぽいですね。
ここに他の拡張子からの変換はどうやるのって書かれてるけど返事ないですね。。
https://github.com/vbenjs/vite-plugin-imagemin/issues/40
