### ISSUE TITLE
partialとcomponentsフォルダについて

### ISSUE THREAD

**Issue by uemaSR** [liginc/wp-starter-theme#24]
これを分けている理由が気になります。どちらも部分という意味で同じだと思うのですが、グローバルかどうかで分けたい感じですか？？
また、パーツフォルダという意味で分けるのであれば、最近のwpデフォルトテーマではpartsが採用されているので、できればネーミングを揃えてpartsにしたいと考えています。
みなさんの意見が聞きたいです！

**Comment by hisamikurita** [comment]
皆さんの意見を聞いてみます！

**Comment by hisamikurita** [comment]
話し合いの結果、WPのアプリケーションの思想に従ってpartsにします。

**Comment by hisamikurita** [comment]
対応済みです！
https://github.com/liginc/wp-starter-theme/pull/35
