### ISSUE TITLE
all-in-one-migration でローカルのDBをまるごとエクスポートしてテストサイトにインポートした時にテーマファイルが「src」になる

### ISSUE THREAD

**Issue by hisamikurita** [liginc/wp-starter-theme#59]

**Comment by uemaSR** [comment]
all-in-one-migration では、運用でテーマフォルダは省くべきです。ci/cdも組まれてるのでおかしなことになりそう。
dbのみとか、プラグインまで含めるとか、運用側で判断して行った方がよいかと。

**Comment by hisamikurita** [comment]
確かにその通りですね😂
Readmeに記載しておこうかな。
