### ISSUE TITLE
bitbucket-pipelines.ymlについて

### ISSUE THREAD

**Issue by uemaSR** [liginc/wp-starter-theme#66]
サンプル書いておいてもらってありがとうございます！
ここの `LOCAL_PATH` って、どのディレクトリをあてるべきですか？
各変数のサンプルも書いておいていただけると非常に助かります！

**Comment by hisamikurita** [comment]
> ここの LOCAL_PATH って、どのディレクトリをあてるべきですか？

`./dist`ですね！ここにビルド後のテーマファイルが出力されるので、それをリモートにアップしていただけたら👌

他の変数はリポジトリによって異なってくるので、下記の記事が辺りが参考になると思います。
(deploy.shなんて設定した記憶がない...他のPJはdeploy.shなしでもパイプライン動いていたはずです)
https://nao550.hateblo.jp/entry/2019/01/08/233420
https://qiita.com/uitspitss/items/4668a964dbedfb2af67e

プルリクも作成しました🔥
https://github.com/liginc/wp-starter-theme/pull/67

**Comment by uemaSR** [comment]
ありがとうございます！
wp本体側じゃなくてミラーリングしてるところで良かったです。
確認します！
