### ISSUE TITLE
プラグインの運用方法について検討

### ISSUE THREAD

**Issue by hisamikurita** [liginc/wp-starter-theme#8]
wp-envに記述するのはやめるか

**Comment by uemaSR** [comment]
プラグインを追加削除するたびに手動で .wp-env.json に書かないといけないのは面倒くさい。
かと言って git でプラグインを共有するのもなんかいやだなーと。
理想を言えば、wpをストップした時に、wp-cliで有効化されているプラグインのリストを取得し、 .wp-env.json の plugins に自動で追記してくれる シェルスクリプト書ければいいなーと。

**Comment by uemaSR** [comment]
wp-cliでプラグインのリストを取得したら、プラグイン名、ステータスなどしか入っておらず、プラグインのURLが無かった。
wp-envのプラグインのところに、プラグイン名だけでいけるかとテストしたところ、NGでした。
自動化は無理っぽいですね。
やっぱり下記のどちらかになりそうです。。

- 手動でプラグインのところに追加削除変更を書いていく
- 自動でプラグインディレクトリをマッピングしてプラグインをgitで管理する

**Comment by uemaSR** [comment]
ACF PRO もURLから初期インストールできないので、これはgitでフォルダ共有しかない気がしてきました。

**Comment by hisamikurita** [comment]
プラグインの運用方法についてもう一度検討したいです。

前提として今回のWPテンプレートは、WordPressのアップデートが常に行われていくこと、運用がLIG以外になる可能性を考慮して互換性に特化したものにしたいです。

現状、初期でインストールしているものは下記になります。
他に必要なものや逆に不必要なものがあれば意見いただきたいです。
==================================================
・all-in-one-wp-migration
・wordpress-seo
・query-monitor
・wp-multibyte-patch
・webp-converter-for-media ← これいらないかな...
・duplicate-post
==================================================

プラグインの管理方法については、以下の三択になるのかなと思っていて、
gitでフォルダ共有した場合は、プラグインのアップデートを意識しないといけないのかなと思ってます。
.wp-env.jsonに記述した場合は常に最新が落とされると思う...
==================================================
・.wp-env.jsonに記述する
・gitでフォルダ共有
・wp-env.jsonに記述する & gitでフォルダ共有
==================================================

ACF PROはGitでフォルダ共有しかないと思うんですが、その場合は公開リポジトリなので、コードが公開されてしまう？
どうやって管理するのがベストでしょうか。

**Comment by uemaSR** [comment]
公開リポジトリだとフォルダ共有は絶対に無しですね。
readmeに手動で入れて下さいみたいなの書いておくしかないかなぁ。

あと、#40 にも関連するのですが、セキュリティプラグイン必須にしたいです。
https://ja.wordpress.org/plugins/all-in-one-wp-security-and-firewall/

前のfunctionsにあるのだけじゃちょっと足りないのと、テーマとは切り離したい感じです。

**Comment by hisamikurita** [comment]
参考になります！検討します！

**Comment by hisamikurita** [comment]
有料プラグインは手動でインストールする方向にしました！
